# Generated by Django 5.0.3 on 2024-04-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_thread_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='content',
            field=models.TextField(default='Asdasdasdasd', max_length=2000),
            preserve_default=False,
        ),
    ]
