# Generated by Django 5.0.3 on 2024-04-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_thread_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='thread',
        ),
    ]
