# Generated by Django 5.0.3 on 2024-04-10 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_rename_post_comment_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(200)]),
        ),
    ]
