# Generated by Django 5.0.3 on 2024-04-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_alter_thread_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
