# Generated by Django 5.0.3 on 2024-04-07 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
