# Generated by Django 5.0.3 on 2024-04-10 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(2000)]),
        ),
    ]
