# Generated by Django 5.0.3 on 2024-04-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='LetUsTalkUserProfile',
        ),
    ]
