# Generated by Django 5.0.3 on 2024-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_letustalkuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letustalkuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
